/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-cisco-ios-xr-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.iosxr.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-ios-xr-id.yang */
public class tailfNedCiscoIosXrId extends ConfNamespace {
    public static final int hash = 715157377;
    public int hash() {
        return tailfNedCiscoIosXrId.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-ios-xr-id";
    public String id() {
        return tailfNedCiscoIosXrId.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-ios-xr-id";
    public String uri() {
        return tailfNedCiscoIosXrId.uri;
    }

    public static final String prefix = "cisco-ios-xr-id";
    public String prefix() {
        return tailfNedCiscoIosXrId.prefix;
    }

    public tailfNedCiscoIosXrId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _cisco_ios_xr = 2122913147;
    public static final String _cisco_ios_xr_ = "cisco-ios-xr";
}
