/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/qos.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.qos.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module qos.yang */
public class qos extends ConfNamespace {
    public static final int hash = 994410121;
    public int hash() {
        return qos.hash;
    }

    public static final String id = "http://com/example/qos";
    public String id() {
        return qos.id;
    }

    public static final String uri = "http://com/example/qos";
    public String uri() {
        return qos.uri;
    }

    public static final String prefix = "qos";
    public String prefix() {
        return qos.prefix;
    }

    public qos() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _config_data = 294526531;
    public static final String _config_data_ = "config-data";
    public static final int    _clear = 634788371;
    public static final String _clear_ = "clear";
    public static final int    _queue_item = 1872384595;
    public static final String _queue_item_ = "queue-item";
    public static final int    _dst_port = 645748677;
    public static final String _dst_port_ = "dst-port";
    public static final int    _native = 472211213;
    public static final String _native_ = "native";
    public static final int    _src_device_name = 2048969054;
    public static final String _src_device_name_ = "src-device-name";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _get_modifications = 1195376060;
    public static final String _get_modifications_ = "get-modifications";
    public static final int    _qos_level = 10755767;
    public static final String _qos_level_ = "qos-level";
    public static final int    _time_out_choice = 1405068132;
    public static final String _time_out_choice_ = "time-out-choice";
    public static final int    _no_overwrite = 2064525500;
    public static final String _no_overwrite_ = "no-overwrite";
    public static final int    _src_port = 557457527;
    public static final String _src_port_ = "src-port";
    public static final int    _ignore_refcount = 911461978;
    public static final String _ignore_refcount_ = "ignore-refcount";
    public static final int    _re_deploy = 1952857006;
    public static final String _re_deploy_ = "re-deploy";
    public static final int    _no_networking = 479600569;
    public static final String _no_networking_ = "no-networking";
    public static final int    _cleared_by_admin = 1307536695;
    public static final String _cleared_by_admin_ = "cleared-by-admin";
    public static final int    _qosname = 77327790;
    public static final String _qosname_ = "qosname";
    public static final int    _device_list = 96950231;
    public static final String _device_list_ = "device-list";
    public static final int    _result_xml = 558977045;
    public static final String _result_xml_ = "result-xml";
    public static final int    _time = 190171445;
    public static final String _time_ = "time";
    public static final int    _src_endpoint = 1515516650;
    public static final String _src_endpoint_ = "src-endpoint";
    public static final int    _error = 126243105;
    public static final String _error_ = "error";
    public static final int    _in_sync = 1179976821;
    public static final String _in_sync_ = "in-sync";
    public static final int    _isNotified = 771315417;
    public static final String _isNotified_ = "isNotified";
    public static final int    _outformat = 2033658489;
    public static final String _outformat_ = "outformat";
    public static final int    _failed_device = 1735357793;
    public static final String _failed_device_ = "failed-device";
    public static final int    _commit_queue = 159457261;
    public static final String _commit_queue_ = "commit-queue";
    public static final int    _lock = 95781586;
    public static final String _lock_ = "lock";
    public static final int    _no_out_of_sync_check = 1635449845;
    public static final String _no_out_of_sync_check_ = "no-out-of-sync-check";
    public static final int    _purge = 521476653;
    public static final String _purge_ = "purge";
    public static final int    _diff_set = 545581821;
    public static final String _diff_set_ = "diff-set";
    public static final int    _block_others = 1263742525;
    public static final String _block_others_ = "block-others";
    public static final int    _operation_mode = 53338359;
    public static final String _operation_mode_ = "operation-mode";
    public static final int    _device_modifications = 2139467807;
    public static final String _device_modifications_ = "device-modifications";
    public static final int    _no_of_impacted_services = 617426878;
    public static final String _no_of_impacted_services_ = "no-of-impacted-services";
    public static final int    _sync = 2047869128;
    public static final String _sync_ = "sync";
    public static final int    _dry_run = 1450488329;
    public static final String _dry_run_ = "dry-run";
    public static final int    _bandwith = 182133945;
    public static final String _bandwith_ = "bandwith";
    public static final int    _un_deploy = 1885839871;
    public static final String _un_deploy_ = "un-deploy";
    public static final int    _no_revision_drop = 355519481;
    public static final String _no_revision_drop_ = "no-revision-drop";
    public static final int    _bypass = 1000536498;
    public static final String _bypass_ = "bypass";
    public static final int    _qos = 2021583496;
    public static final String _qos_ = "qos";
    public static final int    _property = 1802560321;
    public static final String _property_ = "property";
    public static final int    _status = 1950810920;
    public static final String _status_ = "status";
    public static final int    _forward_diff_set = 236345226;
    public static final String _forward_diff_set_ = "forward-diff-set";
    public static final int    _dst_endpoint = 1456884774;
    public static final String _dst_endpoint_ = "dst-endpoint";
    public static final int    _cli = 1771971819;
    public static final String _cli_ = "cli";
    public static final int    _tag = 21925559;
    public static final String _tag_ = "tag";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _async = 1368962940;
    public static final String _async_ = "async";
    public static final int    _re_deploy_counter = 1940885313;
    public static final String _re_deploy_counter_ = "re-deploy-counter";
    public static final int    _infinity = 1378257424;
    public static final String _infinity_ = "infinity";
    public static final int    _used_by_customer_service = 1598928830;
    public static final String _used_by_customer_service_ = "used-by-customer-service";
    public static final int    _private = 2025604902;
    public static final String _private_ = "private";
    public static final int    _check_sync = 1337316030;
    public static final String _check_sync_ = "check-sync";
    public static final int    _timeout = 614210192;
    public static final String _timeout_ = "timeout";
    public static final int    _property_list = 1324655271;
    public static final String _property_list_ = "property-list";
    public static final int    _device = 617911018;
    public static final String _device_ = "device";
    public static final int    _reverse = 1011351090;
    public static final String _reverse_ = "reverse";
    public static final int    _dst_device_name = 834347601;
    public static final String _dst_device_name_ = "dst-device-name";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _data = 535242711;
    public static final String _data_ = "data";
    public static final int    _deep_check_sync = 928241134;
    public static final String _deep_check_sync_ = "deep-check-sync";
    public static final String callpoint_ncs_rfs_service_hook = "ncs-rfs-service-hook";
    public static final String servicepoint_qos_servicepoint = "qos-servicepoint";
}
