/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ../load-dir/tailf-ned-cisco-apicdc.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.example.qos.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-cisco-apicdc.yang */
public class tailfNedCiscoApicdc extends ConfNamespace {
    public static final int hash = 958035285;
    public int hash() {
        return tailfNedCiscoApicdc.hash;
    }

    public static final String id = "http://tail-f.com/ned/cisco-apic";
    public String id() {
        return tailfNedCiscoApicdc.id;
    }

    public static final String uri = "http://tail-f.com/ned/cisco-apic";
    public String uri() {
        return tailfNedCiscoApicdc.uri;
    }

    public static final String prefix = "cisco-apicdc";
    public String prefix() {
        return tailfNedCiscoApicdc.prefix;
    }

    public tailfNedCiscoApicdc() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _sFromPort = 2029089317;
    public static final String _sFromPort_ = "sFromPort";
    public static final int    _vzFilter = 564687916;
    public static final String _vzFilter_ = "vzFilter";
    public static final int    _multiDstPktAct = 1963165779;
    public static final String _multiDstPktAct_ = "multiDstPktAct";
    public static final int    _dvsVersion = 1470455938;
    public static final String _dvsVersion_ = "dvsVersion";
    public static final int    _unkMcastAct = 1254321812;
    public static final String _unkMcastAct_ = "unkMcastAct";
    public static final int    _tcpRules = 1253214311;
    public static final String _tcpRules_ = "tcpRules";
    public static final int    _fromPort = 942650380;
    public static final String _fromPort_ = "fromPort";
    public static final int    _rootContName = 2025231860;
    public static final String _rootContName_ = "rootContName";
    public static final int    _tnVzBrCPName = 738355455;
    public static final String _tnVzBrCPName_ = "tnVzBrCPName";
    public static final int    _mode = 575893728;
    public static final String _mode_ = "mode";
    public static final int    _fvRsCtx = 1925261381;
    public static final String _fvRsCtx_ = "fvRsCtx";
    public static final int    _infraLeafS = 2032729010;
    public static final String _infraLeafS_ = "infraLeafS";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _unkMacUcastAct = 917136577;
    public static final String _unkMacUcastAct_ = "unkMacUcastAct";
    public static final int    _infraRsLacpPol = 1655231490;
    public static final String _infraRsLacpPol_ = "infraRsLacpPol";
    public static final int    _ctrl = 1352953648;
    public static final String _ctrl_ = "ctrl";
    public static final int    _vmmDomP = 898562730;
    public static final String _vmmDomP_ = "vmmDomP";
    public static final int    _arpFlood = 39000560;
    public static final String _arpFlood_ = "arpFlood";
    public static final int    _fvRsPathAtt = 1143444943;
    public static final String _fvRsPathAtt_ = "fvRsPathAtt";
    public static final int    _applyToFrag = 1662281458;
    public static final String _applyToFrag_ = "applyToFrag";
    public static final int    _l2extRsL2DomAtt = 1864704462;
    public static final String _l2extRsL2DomAtt_ = "l2extRsL2DomAtt";
    public static final int    _infraNodeP = 944974346;
    public static final String _infraNodeP_ = "infraNodeP";
    public static final int    _ifInstT = 1420478429;
    public static final String _ifInstT_ = "ifInstT";
    public static final int    _ownerKey = 625329849;
    public static final String _ownerKey_ = "ownerKey";
    public static final int    _l2extInstP = 1039638605;
    public static final String _l2extInstP_ = "l2extInstP";
    public static final int    _l2extOut = 1147330678;
    public static final String _l2extOut_ = "l2extOut";
    public static final int    _l2extLIfP = 794148023;
    public static final String _l2extLIfP_ = "l2extLIfP";
    public static final int    _speed = 1423237997;
    public static final String _speed_ = "speed";
    public static final int    _l2extRsPathL2OutAtt = 1828642666;
    public static final String _l2extRsPathL2OutAtt_ = "l2extRsPathL2OutAtt";
    public static final int    _statsMode = 1188851942;
    public static final String _statsMode_ = "statsMode";
    public static final int    _tDn = 683108692;
    public static final String _tDn_ = "tDn";
    public static final int    _lagT = 1389600242;
    public static final String _lagT_ = "lagT";
    public static final int    _mtu = 1751455506;
    public static final String _mtu_ = "mtu";
    public static final int    _revFltPorts = 417896680;
    public static final String _revFltPorts_ = "revFltPorts";
    public static final int    _fvBD = 2085820643;
    public static final String _fvBD_ = "fvBD";
    public static final int    _dFromPort = 2062772599;
    public static final String _dFromPort_ = "dFromPort";
    public static final int    _addr = 1376787785;
    public static final String _addr_ = "addr";
    public static final int    _infraRsHIfPol = 2088475423;
    public static final String _infraRsHIfPol_ = "infraRsHIfPol";
    public static final int    _unicastRoute = 2022540994;
    public static final String _unicastRoute_ = "unicastRoute";
    public static final int    _vzEntry = 406817004;
    public static final String _vzEntry_ = "vzEntry";
    public static final int    _l3extOut = 85567605;
    public static final String _l3extOut_ = "l3extOut";
    public static final int    _scope = 2046414572;
    public static final String _scope_ = "scope";
    public static final int    _l2extLNodeP = 234714380;
    public static final String _l2extLNodeP_ = "l2extLNodeP";
    public static final int    _matchT = 1094456313;
    public static final String _matchT_ = "matchT";
    public static final int    _tnLacpLagPolName = 1758628891;
    public static final String _tnLacpLagPolName_ = "tnLacpLagPolName";
    public static final int    _toCard = 1524833266;
    public static final String _toCard_ = "toCard";
    public static final int    _autoNeg = 703790140;
    public static final String _autoNeg_ = "autoNeg";
    public static final int    _vzRsSubjFiltAtt = 40801244;
    public static final String _vzRsSubjFiltAtt_ = "vzRsSubjFiltAtt";
    public static final int    _minLinks = 482946830;
    public static final String _minLinks_ = "minLinks";
    public static final int    _hostOrIp = 1152904603;
    public static final String _hostOrIp_ = "hostOrIp";
    public static final int    _baseEncap = 333977876;
    public static final String _baseEncap_ = "baseEncap";
    public static final int    _toPort = 271938811;
    public static final String _toPort_ = "toPort";
    public static final int    _vmmCtrlrP = 517230093;
    public static final String _vmmCtrlrP_ = "vmmCtrlrP";
    public static final int    _tnFabricHIfPolName = 1811147050;
    public static final String _tnFabricHIfPolName_ = "tnFabricHIfPolName";
    public static final int    _mac = 474706838;
    public static final String _mac_ = "mac";
    public static final int    _etherT = 898368456;
    public static final String _etherT_ = "etherT";
    public static final int    _l3extRsPathL3OutAtt = 751859469;
    public static final String _l3extRsPathL3OutAtt_ = "l3extRsPathL3OutAtt";
    public static final int    _fabricHIfPol = 379211825;
    public static final String _fabricHIfPol_ = "fabricHIfPol";
    public static final int    _sToPort = 1419473712;
    public static final String _sToPort_ = "sToPort";
    public static final int    _prot = 2040988365;
    public static final String _prot_ = "prot";
    public static final int    _knwMcastAct = 1658453707;
    public static final String _knwMcastAct_ = "knwMcastAct";
    public static final int    _tnFvBDName = 1030996346;
    public static final String _tnFvBDName_ = "tnFvBDName";
    public static final int    _targetDscp = 260493108;
    public static final String _targetDscp_ = "targetDscp";
    public static final int    _fvRsBd = 1605450010;
    public static final String _fvRsBd_ = "fvRsBd";
    public static final int    _infraRsAccBaseGrp = 562538127;
    public static final String _infraRsAccBaseGrp_ = "infraRsAccBaseGrp";
    public static final int    _port = 10387472;
    public static final String _port_ = "port";
    public static final int    _cisco_apicdc_id = 348041294;
    public static final String _cisco_apicdc_id_ = "cisco-apicdc-id";
    public static final int    _provMatchT = 2017159014;
    public static final String _provMatchT_ = "provMatchT";
    public static final int    _fvAp = 104237100;
    public static final String _fvAp_ = "fvAp";
    public static final int    _ip = 1643785435;
    public static final String _ip_ = "ip";
    public static final int    _linkDebounce = 682660916;
    public static final String _linkDebounce_ = "linkDebounce";
    public static final int    _infraInfra = 377480847;
    public static final String _infraInfra_ = "infraInfra";
    public static final int    _infraNodeBlk = 1135657484;
    public static final String _infraNodeBlk_ = "infraNodeBlk";
    public static final int    _tnVzFilterName = 2050129246;
    public static final String _tnVzFilterName_ = "tnVzFilterName";
    public static final int    _l3extLNodeP = 1996354880;
    public static final String _l3extLNodeP_ = "l3extLNodeP";
    public static final int    _fvRsCons = 387131883;
    public static final String _fvRsCons_ = "fvRsCons";
    public static final int    _mcastAddr = 201356459;
    public static final String _mcastAddr_ = "mcastAddr";
    public static final int    _apic = 1825815541;
    public static final String _apic_ = "apic";
    public static final int    _pcEnfPref = 1006121572;
    public static final String _pcEnfPref_ = "pcEnfPref";
    public static final int    _tnFvCtxName = 1842778284;
    public static final String _tnFvCtxName_ = "tnFvCtxName";
    public static final int    _infraFuncP = 428249163;
    public static final String _infraFuncP_ = "infraFuncP";
    public static final int    _fvCEp = 1604443792;
    public static final String _fvCEp_ = "fvCEp";
    public static final int    _infraHPortS = 1138317208;
    public static final String _infraHPortS_ = "infraHPortS";
    public static final int    _arpOpc = 23656308;
    public static final String _arpOpc_ = "arpOpc";
    public static final int    _vmmProvP = 2058763607;
    public static final String _vmmProvP_ = "vmmProvP";
    public static final int    _fromCard = 543124091;
    public static final String _fromCard_ = "fromCard";
    public static final int    _type = 2040883914;
    public static final String _type_ = "type";
    public static final int    _infraAccPortP = 1112586505;
    public static final String _infraAccPortP_ = "infraAccPortP";
    public static final int    _infraAccPortGrp = 2105129334;
    public static final String _infraAccPortGrp_ = "infraAccPortGrp";
    public static final int    _from_ = 2112098601;
    public static final String _from__ = "from_";
    public static final int    _fvCtx = 5036641;
    public static final String _fvCtx_ = "fvCtx";
    public static final int    _infraAccNodePGrp = 670340991;
    public static final String _infraAccNodePGrp_ = "infraAccNodePGrp";
    public static final int    _resImedcy = 1494799377;
    public static final String _resImedcy_ = "resImedcy";
    public static final int    _infraRsAccPortP = 810418534;
    public static final String _infraRsAccPortP_ = "infraRsAccPortP";
    public static final int    _fvTenant = 1723619597;
    public static final String _fvTenant_ = "fvTenant";
    public static final int    _fvAEPg = 765910295;
    public static final String _fvAEPg_ = "fvAEPg";
    public static final int    _tag = 21925559;
    public static final String _tag_ = "tag";
    public static final int    _fvSubnet = 842361946;
    public static final String _fvSubnet_ = "fvSubnet";
    public static final int    _ownerTag = 1569949588;
    public static final String _ownerTag_ = "ownerTag";
    public static final int    _id = 1279252765;
    public static final String _id_ = "id";
    public static final int    _instrImedcy = 1416510303;
    public static final String _instrImedcy_ = "instrImedcy";
    public static final int    _vzBrCP = 695115525;
    public static final String _vzBrCP_ = "vzBrCP";
    public static final int    _def = 684080477;
    public static final String _def_ = "def";
    public static final int    _fvRsDomAtt = 1894670413;
    public static final String _fvRsDomAtt_ = "fvRsDomAtt";
    public static final int    _infraRsAccNodePGrp = 1993861833;
    public static final String _infraRsAccNodePGrp_ = "infraRsAccNodePGrp";
    public static final int    _l3extLIfP = 736497327;
    public static final String _l3extLIfP_ = "l3extLIfP";
    public static final int    _enfPref = 1638826522;
    public static final String _enfPref_ = "enfPref";
    public static final int    _addressMAC = 1424782034;
    public static final String _addressMAC_ = "addressMAC";
    public static final int    _inventoryTrigSt = 1548263703;
    public static final String _inventoryTrigSt_ = "inventoryTrigSt";
    public static final int    _to_ = 1760886129;
    public static final String _to__ = "to_";
    public static final int    _maxLinks = 157876753;
    public static final String _maxLinks_ = "maxLinks";
    public static final int    _fvRsProv = 836262748;
    public static final String _fvRsProv_ = "fvRsProv";
    public static final int    _adminSt = 1873972966;
    public static final String _adminSt_ = "adminSt";
    public static final int    _infraRsCdpIfPol = 847127855;
    public static final String _infraRsCdpIfPol_ = "infraRsCdpIfPol";
    public static final int    _l2extRsEBd = 2053064064;
    public static final String _l2extRsEBd_ = "l2extRsEBd";
    public static final int    _vzSubj = 691412254;
    public static final String _vzSubj_ = "vzSubj";
    public static final int    _dToPort = 1675344218;
    public static final String _dToPort_ = "dToPort";
    public static final int    _descr = 114576946;
    public static final String _descr_ = "descr";
    public static final int    _infraPortBlk = 837665306;
    public static final String _infraPortBlk_ = "infraPortBlk";
    public static final int    _infraAccBndlGrp = 596268967;
    public static final String _infraAccBndlGrp_ = "infraAccBndlGrp";
    public static final int    _fexId = 1090429334;
    public static final String _fexId_ = "fexId";
    public static final int    _prio = 1618150423;
    public static final String _prio_ = "prio";
    public static final int    _lacpLagPol = 1220562759;
    public static final String _lacpLagPol_ = "lacpLagPol";
    public static final int    _tnCdpIfPolName = 726141211;
    public static final String _tnCdpIfPolName_ = "tnCdpIfPolName";
    public static final int    _vendor = 1639541835;
    public static final String _vendor_ = "vendor";
    public static final int    _consMatchT = 477741482;
    public static final String _consMatchT_ = "consMatchT";
    public static final int    _encap = 1516398699;
    public static final String _encap_ = "encap";
    public static final int    _cdpIfPol = 1442110987;
    public static final String _cdpIfPol_ = "cdpIfPol";
}
