/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/odl.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.odl.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module odl.yang */
public class odl extends ConfNamespace {
    public static final int hash = 52102264;
    public int hash() {
        return odl.hash;
    }

    public static final String id = "http://tail-f.com/ned/odl";
    public String id() {
        return odl.id;
    }

    public static final String uri = "http://tail-f.com/ned/odl";
    public String uri() {
        return odl.uri;
    }

    public static final String prefix = "odl";
    public String prefix() {
        return odl.prefix;
    }

    public odl() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _rpc_remove_lsp = 1048954982;
    public static final String _rpc_remove_lsp_ = "rpc-remove-lsp";
    public static final int    _rpc_add_lsp = 1684960129;
    public static final String _rpc_add_lsp_ = "rpc-add-lsp";
    public static final int    _rpc_remove_lsp_sr = 1569638778;
    public static final String _rpc_remove_lsp_sr_ = "rpc-remove-lsp-sr";
    public static final int    _path_computation_client = 312654919;
    public static final String _path_computation_client_ = "path-computation-client";
    public static final int    _path = 1002915403;
    public static final String _path_ = "path";
    public static final int    _pst = 1482401464;
    public static final String _pst_ = "pst";
    public static final int    _m_flag = 2032219809;
    public static final String _m_flag_ = "m-flag";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _ip_address = 36594129;
    public static final String _ip_address_ = "ip-address";
    public static final int    _lsp_update_capability = 211250160;
    public static final String _lsp_update_capability_ = "lsp-update-capability";
    public static final int    _remove_lsp = 895162436;
    public static final String _remove_lsp_ = "remove-lsp";
    public static final int    _rpc_update_lsp = 1768928494;
    public static final String _rpc_update_lsp_ = "rpc-update-lsp";
    public static final int    _topology_id = 1214815184;
    public static final String _topology_id_ = "topology-id";
    public static final int    _update_lsp_sr = 135724735;
    public static final String _update_lsp_sr_ = "update-lsp-sr";
    public static final int    _administrative = 932198334;
    public static final String _administrative_ = "administrative";
    public static final int    _local_ip_address = 890497179;
    public static final String _local_ip_address_ = "local-ip-address";
    public static final int    _sid = 1233827376;
    public static final String _sid_ = "sid";
    public static final int    _rpc_update_lsp_sr = 1801219246;
    public static final String _rpc_update_lsp_sr_ = "rpc-update-lsp-sr";
    public static final int    _subobject = 1593048295;
    public static final String _subobject_ = "subobject";
    public static final int    _initiation = 423881270;
    public static final String _initiation_ = "initiation";
    public static final int    _destination_ipv6_address = 71291235;
    public static final String _destination_ipv6_address_ = "destination-ipv6-address";
    public static final int    _network_topology = 2070776620;
    public static final String _network_topology_ = "network-topology";
    public static final int    _reported_lsp = 129039348;
    public static final String _reported_lsp_ = "reported-lsp";
    public static final int    _destination_ipv4_address = 804693942;
    public static final String _destination_ipv4_address_ = "destination-ipv4-address";
    public static final int    _ipv4_case = 1413514427;
    public static final String _ipv4_case_ = "ipv4-case";
    public static final int    _source_ipv4_address = 288197810;
    public static final String _source_ipv4_address_ = "source-ipv4-address";
    public static final int    _rpc_add_lsp_sr = 1218574265;
    public static final String _rpc_add_lsp_sr_ = "rpc-add-lsp-sr";
    public static final int    _address_family = 203507431;
    public static final String _address_family_ = "address-family";
    public static final int    _ip_prefix = 289539202;
    public static final String _ip_prefix_ = "ip-prefix";
    public static final int    _ipv6 = 1228132394;
    public static final String _ipv6_ = "ipv6";
    public static final int    _source_ipv6_address = 252700970;
    public static final String _source_ipv6_address_ = "source-ipv6-address";
    public static final int    _remote_ip_address = 1221714707;
    public static final String _remote_ip_address_ = "remote-ip-address";
    public static final int    _ero = 297555401;
    public static final String _ero_ = "ero";
    public static final int    _ipv6_case = 1385397181;
    public static final String _ipv6_case_ = "ipv6-case";
    public static final int    _update_lsp = 705577019;
    public static final String _update_lsp_ = "update-lsp";
    public static final int    _sid_type = 1509168687;
    public static final String _sid_type_ = "sid-type";
    public static final int    _delegate = 1742952712;
    public static final String _delegate_ = "delegate";
    public static final int    _node = 2084421367;
    public static final String _node_ = "node";
    public static final int    _node_id = 98319925;
    public static final String _node_id_ = "node-id";
    public static final int    _add_lsp_sr = 172670739;
    public static final String _add_lsp_sr_ = "add-lsp-sr";
    public static final int    _lsp_id = 463300792;
    public static final String _lsp_id_ = "lsp-id";
    public static final int    _endpoints_obj = 809307229;
    public static final String _endpoints_obj_ = "endpoints-obj";
    public static final int    _remove_lsp_sr = 803816847;
    public static final String _remove_lsp_sr_ = "remove-lsp-sr";
    public static final int    _stateful_tlv = 1946982387;
    public static final String _stateful_tlv_ = "stateful-tlv";
    public static final int    _odl_id = 397964850;
    public static final String _odl_id_ = "odl-id";
    public static final int    _ipv4 = 268057062;
    public static final String _ipv4_ = "ipv4";
    public static final int    _lsp = 2093596695;
    public static final String _lsp_ = "lsp";
    public static final int    _loose = 1823994566;
    public static final String _loose_ = "loose";
    public static final int    _operation_result = 99750145;
    public static final String _operation_result_ = "operation-result";
    public static final int    _arguments = 305502020;
    public static final String _arguments_ = "arguments";
    public static final int    _state_sync = 1926891798;
    public static final String _state_sync_ = "state-sync";
    public static final int    _pcep_topology = 1939779717;
    public static final String _pcep_topology_ = "pcep-topology";
    public static final int    _stateful = 1523416178;
    public static final String _stateful_ = "stateful";
    public static final int    _path_setup_type = 1834309513;
    public static final String _path_setup_type_ = "path-setup-type";
    public static final int    _add_lsp = 221031086;
    public static final String _add_lsp_ = "add-lsp";
}
