/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/odl-stats.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.odl.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module odl-stats.yang */
public class odlStats extends ConfNamespace {
    public static final int hash = 1418991684;
    public int hash() {
        return odlStats.hash;
    }

    public static final String id = "http://com/tailf/packages/ned/odl-stats";
    public String id() {
        return odlStats.id;
    }

    public static final String uri = "http://com/tailf/packages/ned/odl-stats";
    public String uri() {
        return odlStats.uri;
    }

    public static final String prefix = "odlstats";
    public String prefix() {
        return odlStats.prefix;
    }

    public odlStats() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _item = 1470352621;
    public static final String _item_ = "item";
    public static final int    _test_stats = 655854080;
    public static final String _test_stats_ = "test-stats";
    public static final int    _i = 1541010383;
    public static final String _i_ = "i";
}
