/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-odl-controller-id.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.odlcontroller.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-odl-controller-id.yang */
public class tailfNedOdlControllerId extends ConfNamespace {
    public static final int hash = 182345625;
    public int hash() {
        return tailfNedOdlControllerId.hash;
    }

    public static final String id = "http://tail-f.com/ned/odl-controller-id";
    public String id() {
        return tailfNedOdlControllerId.id;
    }

    public static final String uri = "http://tail-f.com/ned/odl-controller-id";
    public String uri() {
        return tailfNedOdlControllerId.uri;
    }

    public static final String prefix = "odl-controller-id";
    public String prefix() {
        return tailfNedOdlControllerId.prefix;
    }

    public tailfNedOdlControllerId() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _odl_controller = 808942532;
    public static final String _odl_controller_ = "odl-controller";
}
