/*
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 * This file has been auto-generated by the confdc compiler.
 * Source: ncsc-out/modules/fxs/tailf-ned-odl-controller.fxs
 * BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE BEWARE
 */

package com.tailf.packages.ned.odlcontroller.namespaces;

import com.tailf.conf.ConfNamespace;

/** Autogenerated namespace class for YANG module tailf-ned-odl-controller.yang */
public class tailfNedOdlController extends ConfNamespace {
    public static final int hash = 2047941349;
    public int hash() {
        return tailfNedOdlController.hash;
    }

    public static final String id = "http://tail-f.com/ned/odl-controller";
    public String id() {
        return tailfNedOdlController.id;
    }

    public static final String uri = "http://tail-f.com/ned/odl-controller";
    public String uri() {
        return tailfNedOdlController.uri;
    }

    public static final String prefix = "odl-controller";
    public String prefix() {
        return tailfNedOdlController.prefix;
    }

    public tailfNedOdlController() {}

    public static int stringToHash(String str) {
        return ConfNamespace.stringToHash(str);
    }

    public static String hashToString(int hash) {
        return ConfNamespace.hashToString(hash);
    }

    public static final int    _RLOCProbe = 622622862;
    public static final String _RLOCProbe_ = "RLOCProbe";
    public static final int    _localLocator = 569621341;
    public static final String _localLocator_ = "localLocator";
    public static final int    _Addresses = 150045434;
    public static final String _Addresses_ = "Addresses";
    public static final int    _remove_key = 1332810305;
    public static final String _remove_key_ = "remove-key";
    public static final int    _remotePortHigh = 1151829175;
    public static final String _remotePortHigh_ = "remotePortHigh";
    public static final int    _iidMaskLength = 449918684;
    public static final String _iidMaskLength_ = "iidMaskLength";
    public static final int    _rpc_remove_key = 1977757657;
    public static final String _rpc_remove_key_ = "rpc-remove-key";
    public static final int    _lcafType = 1794422906;
    public static final String _lcafType_ = "lcafType";
    public static final int    _rpc_add_key = 285129223;
    public static final String _rpc_add_key_ = "rpc-add-key";
    public static final int    _dstAddress = 935910764;
    public static final String _dstAddress_ = "dstAddress";
    public static final int    _NoAddress = 1853664566;
    public static final String _NoAddress_ = "NoAddress";
    public static final int    _ASAddress = 671819238;
    public static final String _ASAddress_ = "ASAddress";
    public static final int    _remove_mapping = 490158399;
    public static final String _remove_mapping_ = "remove-mapping";
    public static final int    _recordTtl = 1923838307;
    public static final String _recordTtl_ = "recordTtl";
    public static final int    _name = 1998270519;
    public static final String _name_ = "name";
    public static final int    _authoritative = 2087867227;
    public static final String _authoritative_ = "authoritative";
    public static final int    _multicastPriority = 1923241586;
    public static final String _multicastPriority_ = "multicastPriority";
    public static final int    _Mac = 994695289;
    public static final String _Mac_ = "Mac";
    public static final int    _action = 571883887;
    public static final String _action_ = "action";
    public static final int    _instance_id_context = 729640665;
    public static final String _instance_id_context_ = "instance-id-context";
    public static final int    _multicastWeight = 1154688182;
    public static final String _multicastWeight_ = "multicastWeight";
    public static final int    _srcMaskLength = 1595147616;
    public static final String _srcMaskLength_ = "srcMaskLength";
    public static final int    _rpc_add_mapping = 1502733361;
    public static final String _rpc_add_mapping_ = "rpc-add-mapping";
    public static final int    _LocatorRecord = 1186629322;
    public static final String _LocatorRecord_ = "LocatorRecord";
    public static final int    _Ipv6Address = 523835590;
    public static final String _Ipv6Address_ = "Ipv6Address";
    public static final int    _maskLength = 1579155395;
    public static final String _maskLength_ = "maskLength";
    public static final int    _LcafTrafficEngineeringAddr = 638329643;
    public static final String _LcafTrafficEngineeringAddr_ = "LcafTrafficEngineeringAddr";
    public static final int    _priority = 1346277862;
    public static final String _priority_ = "priority";
    public static final int    _distinguishedName = 128486435;
    public static final String _distinguishedName_ = "distinguishedName";
    public static final int    _localPortHigh = 1532247024;
    public static final String _localPortHigh_ = "localPortHigh";
    public static final int    _output = 171341581;
    public static final String _output_ = "output";
    public static final int    _LispAddressContainer = 1952045937;
    public static final String _LispAddressContainer_ = "LispAddressContainer";
    public static final int    _LcafSourceDestAddr = 2078983132;
    public static final String _LcafSourceDestAddr_ = "LcafSourceDestAddr";
    public static final int    _LcafKeyValueAddressAddr = 1545555089;
    public static final String _LcafKeyValueAddressAddr_ = "LcafKeyValueAddressAddr";
    public static final int    _protocol = 943257313;
    public static final String _protocol_ = "protocol";
    public static final int    _Ipv6 = 1558037165;
    public static final String _Ipv6_ = "Ipv6";
    public static final int    _DistinguishedNameAddress = 845433933;
    public static final String _DistinguishedNameAddress_ = "DistinguishedNameAddress";
    public static final int    _key = 1348858669;
    public static final String _key_ = "key";
    public static final int    _rlocProbed = 691649839;
    public static final String _rlocProbed_ = "rlocProbed";
    public static final int    _rpc_get_key = 547262607;
    public static final String _rpc_get_key_ = "rpc-get-key";
    public static final int    _LcafSourceDest = 505854750;
    public static final String _LcafSourceDest_ = "LcafSourceDest";
    public static final int    _LcafTrafficEngineering = 357664659;
    public static final String _LcafTrafficEngineering_ = "LcafTrafficEngineering";
    public static final int    _LcafSegment = 44314690;
    public static final String _LcafSegment_ = "LcafSegment";
    public static final int    _hop = 1808618560;
    public static final String _hop_ = "hop";
    public static final int    _LcafApplicationData = 110080226;
    public static final String _LcafApplicationData_ = "LcafApplicationData";
    public static final int    _weight = 306158986;
    public static final String _weight_ = "weight";
    public static final int    _get_mapping = 818018530;
    public static final String _get_mapping_ = "get-mapping";
    public static final int    _Hops = 933172156;
    public static final String _Hops_ = "Hops";
    public static final int    _rpc_get_mapping = 1538832453;
    public static final String _rpc_get_mapping_ = "rpc-get-mapping";
    public static final int    _primitiveAddress = 1694410199;
    public static final String _primitiveAddress_ = "primitiveAddress";
    public static final int    _result = 401396173;
    public static final String _result_ = "result";
    public static final int    _authkey = 1978876946;
    public static final String _authkey_ = "authkey";
    public static final int    _LcafApplicationDataAddr = 1986874981;
    public static final String _LcafApplicationDataAddr_ = "LcafApplicationDataAddr";
    public static final int    _LcafListAddr = 1606395248;
    public static final String _LcafListAddr_ = "LcafListAddr";
    public static final int    _update_mapping = 812365586;
    public static final String _update_mapping_ = "update-mapping";
    public static final int    _lookup = 92632502;
    public static final String _lookup_ = "lookup";
    public static final int    _rpc_remove_mapping = 1937513504;
    public static final String _rpc_remove_mapping_ = "rpc-remove-mapping";
    public static final int    _Address = 860170266;
    public static final String _Address_ = "Address";
    public static final int    _eid_context = 684118380;
    public static final String _eid_context_ = "eid-context";
    public static final int    _No = 297576442;
    public static final String _No_ = "No";
    public static final int    _eid = 2032990265;
    public static final String _eid_ = "eid";
    public static final int    _mask_length = 575140370;
    public static final String _mask_length_ = "mask-length";
    public static final int    _LcafList = 797992458;
    public static final String _LcafList_ = "LcafList";
    public static final int    _instanceId = 1733191434;
    public static final String _instanceId_ = "instanceId";
    public static final int    _localPortLow = 882963530;
    public static final String _localPortLow_ = "localPortLow";
    public static final int    _dstMaskLength = 146711743;
    public static final String _dstMaskLength_ = "dstMaskLength";
    public static final int    _Ipv4Address = 1512374320;
    public static final String _Ipv4Address_ = "Ipv4Address";
    public static final int    _update_key = 344736851;
    public static final String _update_key_ = "update-key";
    public static final int    _rpc_update_mapping = 2002455961;
    public static final String _rpc_update_mapping_ = "rpc-update-mapping";
    public static final int    _add_key = 27129322;
    public static final String _add_key_ = "add-key";
    public static final int    _MacAddress = 2029898520;
    public static final String _MacAddress_ = "MacAddress";
    public static final int    _AS = 1289993190;
    public static final String _AS_ = "AS";
    public static final int    _DistinguishedName = 379193930;
    public static final String _DistinguishedName_ = "DistinguishedName";
    public static final int    _strict = 1546810210;
    public static final String _strict_ = "strict";
    public static final int    _get_key = 1117154383;
    public static final String _get_key_ = "get-key";
    public static final int    _afi = 1110348992;
    public static final String _afi_ = "afi";
    public static final int    _remotePortLow = 1105603178;
    public static final String _remotePortLow_ = "remotePortLow";
    public static final int    _ipTos = 1772814216;
    public static final String _ipTos_ = "ipTos";
    public static final int    _mapVersion = 1377833478;
    public static final String _mapVersion_ = "mapVersion";
    public static final int    _rpc_update_key = 2139858921;
    public static final String _rpc_update_key_ = "rpc-update-key";
    public static final int    _key_type = 1387082021;
    public static final String _key_type_ = "key-type";
    public static final int    _add_mapping = 940213213;
    public static final String _add_mapping_ = "add-mapping";
    public static final int    _LcafSegmentAddr = 2058408932;
    public static final String _LcafSegmentAddr_ = "LcafSegmentAddr";
    public static final int    _srcAddress = 2068833991;
    public static final String _srcAddress_ = "srcAddress";
    public static final int    _Ipv4 = 1934818363;
    public static final String _Ipv4_ = "Ipv4";
    public static final int    _value = 864367181;
    public static final String _value_ = "value";
    public static final int    _LcafKeyValue = 1468790222;
    public static final String _LcafKeyValue_ = "LcafKeyValue";
    public static final int    _routed = 1703558057;
    public static final String _routed_ = "routed";
}
